apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: frosty-violet
  namespace: acorn
spec:
  image: ghcr.io/cloudnautique/webhook-demo:v0.0.2
  ports:
  - protocol: http
    publish: true
    serviceName: webhook.mc.cloudnautique.com
    targetServiceName: default
  services:
  - service: mongo
    target: mongo
