apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: fragrant-wave
  namespace: acorn
spec:
  image: ghcr.io/cloudnautique/webhook-demo:v0.0.1
  ports:
  - protocol: http
    publish: true
    serviceName: webhook.mc.cloudnautique.com
    targetServiceName: www
